/* =============================================================================
   build-seo.mjs — the tags a search engine and a chat app read
   -----------------------------------------------------------------------------
   Every page already states its own <title>, description and canonical. Those
   are the truth; everything here is derived from them, so the two can never
   drift apart and a new page needs nothing but its own head.

   What it writes, between the @seo markers:

     Open Graph + Twitter   what WhatsApp, Facebook, X and LinkedIn read when
                            someone pastes a link. None of them run JavaScript,
                            so this has to be in the served HTML.
     JSON-LD (homepage)     tells Google the site's NAME, so a result reads
                            "The Almail Family" rather than the bare domain.

   Pages carrying <meta name="robots" content="noindex"> are skipped: the 404
   and the /home/ redirect are not meant to be shared or indexed.

   Run by `npm run build`, before the asset stamper.
   ========================================================================== */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://almailfamily.com";
const NAME = "The Almail Family";
const CARD = SITE + "/assets/img/share-card.png";
const CARD_ALT = "The Almail family mark — a dhow whose sails are the family name in Arabic";

async function pages(dir = root, base = "") {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.name === "node_modules" || e.name.startsWith(".")) continue;
    const rel = base ? `${base}/${e.name}` : e.name;
    if (e.isDirectory()) out.push(...(await pages(join(dir, e.name), rel)));
    else if (e.name.endsWith(".html")) out.push(rel);
  }
  return out;
}

const pick = (html, re) => (html.match(re) || [, ""])[1].trim();
const esc = (s) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;")
                    .replace(/</g, "&lt;").replace(/>/g, "&gt;");

/* The homepage is the only page that should claim to BE the site. Saying it on
   every page invites Google to pick whichever it likes as the name. */
function jsonLd(canonical, description) {
  if (canonical !== SITE + "/") return "";
  const data = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: NAME,
    alternateName: ["Almail Family", "Almail", "عائلة الميل"],
    url: SITE + "/",
    description,
    inLanguage: ["en", "ar"],
    publisher: { "@type": "Organization", name: NAME, url: SITE + "/", logo: CARD },
  };
  return '  <script type="application/ld+json">\n' +
         JSON.stringify(data, null, 2).split("\n").map((l) => "  " + l).join("\n") +
         "\n  </script>\n";
}

let changed = 0, skipped = 0;
for (const rel of await pages()) {
  const file = join(root, rel);
  let html = await readFile(file, "utf8");

  if (/name="robots"\s+content="noindex"/.test(html)) { skipped++; continue; }

  const title = pick(html, /<title>([^<]*)<\/title>/);
  const desc = pick(html, /<meta name="description" content="([^"]*)"/);
  const canonical = pick(html, /<link rel="canonical" href="([^"]*)"/);
  if (!title || !canonical) { skipped++; continue; }

  /* A page may already say something shorter and better for a share card than
     its meta description. Keep it if so. */
  const ogTitle = pick(html, /<meta property="og:title" content="([^"]*)"/) || title;
  const ogDesc = pick(html, /<meta property="og:description" content="([^"]*)"/) || desc;

  const block =
    "  <!-- @seo — generated by scripts/build-seo.mjs; edit the title," +
    " description\n       and canonical above instead, then run `npm run build`. -->\n" +
    `  <meta property="og:type" content="website">\n` +
    `  <meta property="og:site_name" content="${esc(NAME)}">\n` +
    `  <meta property="og:locale" content="en_GB">\n` +
    `  <meta property="og:locale:alternate" content="ar_KW">\n` +
    `  <meta property="og:url" content="${esc(canonical)}">\n` +
    `  <meta property="og:title" content="${esc(ogTitle)}">\n` +
    `  <meta property="og:description" content="${esc(ogDesc)}">\n` +
    `  <meta property="og:image" content="${CARD}">\n` +
    `  <meta property="og:image:width" content="1200">\n` +
    `  <meta property="og:image:height" content="630">\n` +
    `  <meta property="og:image:alt" content="${esc(CARD_ALT)}">\n` +
    `  <meta name="twitter:card" content="summary_large_image">\n` +
    `  <meta name="twitter:title" content="${esc(ogTitle)}">\n` +
    `  <meta name="twitter:description" content="${esc(ogDesc)}">\n` +
    `  <meta name="twitter:image" content="${CARD}">\n` +
    jsonLd(canonical, ogDesc || desc) +
    "  <!-- @endseo -->\n";

  let next;
  if (html.includes("<!-- @seo")) {
    next = html.replace(/[ \t]*<!-- @seo[\s\S]*?<!-- @endseo -->\n/, block);
  } else {
    /* First run: clear the hand-written tags this replaces, then seat the
       block directly under the canonical. */
    next = html
      .replace(/[ \t]*<!-- Open Graph -->\n/g, "")
      .replace(/[ \t]*<meta property="og:[^"]*"[^>]*>\n/g, "")
      .replace(/[ \t]*<meta name="twitter:[^"]*"[^>]*>\n/g, "")
      .replace(/(<link rel="canonical"[^>]*>\n)/, `$1\n${block}`);
  }

  if (next !== html) { await writeFile(file, next); changed++; }
}
console.log(`seo: ${changed} page(s) written, ${skipped} skipped (noindex or no canonical).`);
